### ISSUE TITLE
Need info

### ISSUE THREAD

**Issue by contirol** [timahey/project-1#6]
It's is a virus?
@timahey

**Comment by timahey** [comment]
No. Why?

**Comment by contirol** [comment]
Well, because it's looks scary

**Comment by timahey** [comment]
> Well, because it's looks scary
![image](https://user-images.githubusercontent.com/69219228/209448650-df5b9f08-70e2-4c54-8ba3-ea16ee74f565.png)

**Comment by timahey** [comment]
And yet, this is GitHub, you can see the source code

**Comment by contirol** [comment]
Okay
